version: '3.3'

volumes:
  postgres_data:
  socket_volume:

services:
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    build: .
    restart: always
    command: uwsgi --ini uwsgi_config.ini
#    command: python manage.py runserver 0.0.0.0:6002
    ports:
      - 6002:6002
    volumes:
      - ./src/static:/app/static
      - ./src/media:/app/media
      - socket_volume:/run/uwsgi
      - ./src:/app
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./src/static:/app/static
      - ./src/media:/app/media
      - socket_volume:/run/uwsgi
    ports:
      - ${NGINX_PUBLIC_PORT}:80
    depends_on:
      - web