version: '3.3'

volumes:
  postgres_data:
  static_volume:
  media_volume:
  socket_volume:

services:
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    build: .
    restart: always
    command: uwsgi --ini uwsgi_config.ini
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - socket_volume:/run/uwsgi
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - socket_volume:/run/uwsgi
    ports:
      - ${NGINX_PUBLIC_PORT}:80
    depends_on:
      - web