# Generated by Django 4.1.2 on 2022-10-19 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hasker', '0003_userquestionrating_question_rating_alter_tag_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_date', 'rating'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='hasker.question', verbose_name='Вопрос'),
            preserve_default=False,
        ),
    ]
