# Generated by Django 4.1.2 on 2022-10-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasker', '0004_alter_answer_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswerrating',
            name='is_like',
            field=models.BooleanField(default=True, verbose_name='Лайк/Дизлайк'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userquestionrating',
            name='is_like',
            field=models.BooleanField(default=True, verbose_name='Лайк/Дизлайк'),
            preserve_default=False,
        ),
    ]
