# Generated by Django 4.1.2 on 2022-10-25 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hasker', '0005_useranswerrating_is_like_userquestionrating_is_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_date', '-rating'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
    ]
